baseURL = "https://msdahlblog.github.io/my-blog/"
languageCode = "da-dk"
title = "My Blog"
theme = "PaperMod"

[params]
  mainSections = ["posts"]
  
  [params.homeInfoParams]
  Title = "Welcome to My Blog"
  Content = "This is my personal blog. I'll be posting content regularly via email."

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
