baseURL = "https://blog.msdahl.net/"
languageCode = "da-dk"
title = "Michael S. Dahls blog"
theme = "PaperMod"
defaultContentLanguage = "da"

# Allow raw HTML in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Suppress HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

# All params should be in a single section
[params]
  mainSections = ["posts"]
  dateFormat = "2. January 2006"
  customCSS = ["css/custom.css"]
  
  [params.homeInfoParams]
  Title = "En professors blog om strategi, ledelse og økonomi"
  Content = "Mine egne tanker om aktuelle strategiske udfordringer, særligt i sport, med reference til aktuelt og nyere forskning. Alt kan diskuteres, så tag det ikke for mere end et indspark til debatten."

# Language settings
[languages]
  [languages.da]
    languageName = "Dansk"
    weight = 1
    
    # Danish date and time formats
    [languages.da.params]
      dateFormat = "2. January 2006"
      monthNames = ["Januar", "Februar", "Marts", "April", "Maj", "Juni", "Juli", "August", "September", "Oktober", "November", "December"]
      shortMonthNames = ["Jan", "Feb", "Mar", "Apr", "Maj", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec"]
      dayNames = ["Søndag", "Mandag", "Tirsdag", "Onsdag", "Torsdag", "Fredag", "Lørdag"]
      shortDayNames = ["Søn", "Man", "Tir", "Ons", "Tor", "Fre", "Lør"]

# Menu settings
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Indlæg"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Om"
    url = "/about/"
    weight = 20
