baseURL = "https://blog.msdahl.net/"
languageCode = "da-dk"
title = "Michael S. Dahls blog"
theme = "PaperMod"

# Add this to ensure proper resource loading
canonifyURLs = true

[params]
  mainSections = ["posts"]
  
  [params.homeInfoParams]
  Title = "En professors blog om strategi, ledelse og økonomi"
  Content = "Mine egne tanker om aktuelle strategiske udfordringer, særligt i sport, med reference til aktuelt og nyere forskning. Alt kan diskuteres, så tag det ikke for mere end et indspark til debatten."

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Indlæg"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Om"
    url = "/about/"
    weight = 20


# Allow raw HTML in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Suppress HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

