name: Email to Blog Post

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # This line grants permission to push to the repository

jobs:
  check-email-and-post:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install imap mailparser slugify

      - name: Check email and create posts
        run: node .github/scripts/email-to-post.js
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          ALLOWED_SENDERS: ${{ secrets.ALLOWED_SENDERS }}
          
      - name: Commit and push if there are changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add content/posts/
          if ! git diff --quiet && ! git diff --staged --quiet; then
            git commit -m "Add new post from email"
            git push
            echo "changes_made=true" >> $GITHUB_OUTPUT
          else
            echo "changes_made=false" >> $GITHUB_OUTPUT
          fi
            
      - name: Trigger Hugo build
        if: steps.commit.outputs.changes_made == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: rebuild-site
